!!python/object:argparse.Namespace
batch_size: 8
board_interval: 50
checkpoint_path: ./pretrained_models/psp_celebs_sketch_to_face.pt
couple_outputs: true
data_path: ./datasets/Edge2anime_small_dataset
dataset_type: celebs_sketch_to_face
device: cuda:0
encoder_type: GradualStyleEncoder
exp_dir: result/result_edge_paper
id_lambda: 0.0
image_interval: 100
input_nc: 1
l2_lambda: 1.0
l2_lambda_crop: 0
label_nc: 1
latent_mask: null
learn_in_w: false
learning_rate: 0.0001
lpips_lambda: 0.8
lpips_lambda_crop: 0
max_steps: 80000
mix_alpha: null
n_images: null
n_outputs_to_generate: 5
optim_name: ranger
output_size: 1024
resize_factors: null
resize_outputs: false
save_interval: 10000
start_from_latent_avg: true
stylegan_weights: ''
test_batch_size: 1
test_workers: 4
train_decoder: false
val_interval: 5000
w_norm_lambda: 0.005
workers: 8
